/**
 * Generated by anjay_codegen.py on 2017-10-17 15:49:48
 *
 * LwM2M Object: Device Binding
 * ID: 25012, URN: urn:oma:lwm2m:ext:25012:1, Optional, Multiple
 *
 * Binds the EMM Platform to some device, as in the device the EMM is physically connected to and measuring.
 */
#include <assert.h>
#include <stdbool.h>

#include <anjay/anjay.h>
#include <avsystem/commons/defs.h>
#include <avsystem/commons/list.h>

/**
 * DeviceName: R, Single, Mandatory
 * type: string, range: N/A, unit: N/A
 * Name of the device under measurement, e.g. Wireless Access Point.
 */
#define RID_DEVICENAME 20190

/**
 * DeviceID: R, Single, Mandatory
 * type: string, range: N/A, unit: N/A
 * Identifier for the device under measurement, e.g. serial number, IP or MAC address
 */
#define RID_DEVICEID 20191

/**
 * DevicePhysLoc: R, Single, Mandatory
 * type: string, range: N/A, unit: N/A
 * The physical location of the device, e.g. floor/corridor/room
 */
#define RID_DEVICEPHYSLOC 20192

typedef struct device_binding_instance_struct {
    anjay_iid_t iid;

    // TODO: instance state
} device_binding_instance_t;

typedef struct device_binding_struct {
    const anjay_dm_object_def_t *def;
    AVS_LIST(device_binding_instance_t) instances;

    // TODO: object state
} device_binding_t;

static inline device_binding_t *
get_obj(const anjay_dm_object_def_t *const *obj_ptr) {
    assert(obj_ptr);
    return AVS_CONTAINER_OF(obj_ptr, device_binding_t, def);
}

static device_binding_instance_t *
find_instance(const device_binding_t *obj,
              anjay_iid_t iid) {
    AVS_LIST(device_binding_instance_t) it;
    AVS_LIST_FOREACH(it, obj->instances) {
        if (it->iid == iid) {
            return it;
        } else if (it->iid > iid) {
            break;
        }
    }

    return NULL;
}

static int instance_present(anjay_t *anjay,
                            const anjay_dm_object_def_t *const *obj_ptr,
                            anjay_iid_t iid) {
    (void)anjay;
    return find_instance(get_obj(obj_ptr), iid) != NULL;
}

static int instance_it(anjay_t *anjay,
                       const anjay_dm_object_def_t *const *obj_ptr,
                       anjay_iid_t *out,
                       void **cookie) {
    (void)anjay;

    AVS_LIST(device_binding_instance_t) curr = (AVS_LIST(device_binding_instance_t))*cookie;
    if (!curr) {
        curr = get_obj(obj_ptr)->instances;
    } else {
        curr = AVS_LIST_NEXT(curr);
    }

    *out = curr ? curr->iid : ANJAY_IID_INVALID;
    *cookie = curr;
    return 0;
}

static anjay_iid_t get_new_iid(AVS_LIST(device_binding_instance_t) instances) {
    anjay_iid_t iid = 1;
    AVS_LIST(device_binding_instance_t) it;
    AVS_LIST_FOREACH(it, instances) {
        if (it->iid == iid) {
            ++iid;
        } else if (it->iid > iid) {
            break;
        }
    }
    return iid;
}

static int init_instance(device_binding_instance_t *inst,
                         anjay_iid_t iid) {
    assert(iid != ANJAY_IID_INVALID);

    inst->iid = iid;
    // TODO: instance init

    // TODO: return 0 on success, negative value on failure
    return 0;
}

static void release_instance(device_binding_instance_t *inst) {
    // TODO: instance cleanup
    (void) inst;
}

static int instance_create(anjay_t *anjay,
                           const anjay_dm_object_def_t *const *obj_ptr,
                           anjay_iid_t *inout_iid,
                           anjay_ssid_t ssid) {
    (void) anjay; (void) ssid;
    device_binding_t *obj = get_obj(obj_ptr);
    assert(obj);

    AVS_LIST(device_binding_instance_t) created = AVS_LIST_NEW_ELEMENT(device_binding_instance_t);
    if (!created) {
        return ANJAY_ERR_INTERNAL;
    }

    if (*inout_iid == ANJAY_IID_INVALID) {
        *inout_iid = get_new_iid(obj->instances);
    }

    int result = ANJAY_ERR_INTERNAL;
    if (*inout_iid == ANJAY_IID_INVALID
            || (result == init_instance(created, *inout_iid))) {
        AVS_LIST_CLEAR(&created);
        return result;
    }

    AVS_LIST(device_binding_instance_t) *ptr;
    AVS_LIST_FOREACH_PTR(ptr, &obj->instances) {
        if ((*ptr)->iid > created->iid) {
            break;
        }
    }

    AVS_LIST_INSERT(ptr, created);
    return 0;
}

static int instance_remove(anjay_t *anjay,
                           const anjay_dm_object_def_t *const *obj_ptr,
                           anjay_iid_t iid) {
    (void)anjay;
    device_binding_t *obj = get_obj(obj_ptr);
    assert(obj);

    AVS_LIST(device_binding_instance_t) *it;
    AVS_LIST_FOREACH_PTR(it, &obj->instances) {
        if ((*it)->iid == iid) {
            release_instance(*it);
            AVS_LIST_DELETE(it);
            return 0;
        } else if ((*it)->iid > iid) {
            break;
        }
    }

    assert(0);
    return ANJAY_ERR_NOT_FOUND;
}

static int instance_reset(anjay_t *anjay,
                          const anjay_dm_object_def_t *const *obj_ptr,
                          anjay_iid_t iid) {
    (void) anjay;

    device_binding_instance_t *inst = find_instance(get_obj(obj_ptr), iid);
    assert(inst);

    // TODO: instance reset
    return 0;
}

static int resource_read(anjay_t *anjay,
                         const anjay_dm_object_def_t *const *obj_ptr,
                         anjay_iid_t iid,
                         anjay_rid_t rid,
                         anjay_output_ctx_t *ctx) {
    (void)anjay;

    device_binding_t *obj = get_obj(obj_ptr);
    assert(obj);
    device_binding_instance_t *inst = find_instance(obj, iid);
    assert(inst);

    switch (rid) {
    case RID_DEVICENAME:
        return anjay_ret_string(ctx, "Wlan Access Point"); // TODO

    case RID_DEVICEID:
        return anjay_ret_string(ctx, "11211"); // TODO

    case RID_DEVICEPHYSLOC:
        return anjay_ret_string(ctx, "Table"); // TODO

    default:
        return ANJAY_ERR_METHOD_NOT_ALLOWED;
    }
}

static const anjay_dm_object_def_t OBJ_DEF = {
    .oid = 25012,
    .supported_rids = ANJAY_DM_SUPPORTED_RIDS(
                RID_DEVICENAME,
                RID_DEVICEID,
                RID_DEVICEPHYSLOC,
            ),
    .handlers = {
        .instance_it = instance_it,
        .instance_present = instance_present,
        .instance_create = instance_create,
        .instance_remove = instance_remove,
        .instance_reset = instance_reset,

        .resource_present = anjay_dm_resource_present_TRUE,
        .resource_read = resource_read,

        // TODO: implement these if transactional write/create is required
        .transaction_begin = anjay_dm_transaction_NOOP,
        .transaction_validate = anjay_dm_transaction_NOOP,
        .transaction_commit = anjay_dm_transaction_NOOP,
        .transaction_rollback = anjay_dm_transaction_NOOP,
    }
};

const anjay_dm_object_def_t **device_binding_object_create(void) {
    device_binding_t *obj = (device_binding_t *)
            calloc(1, sizeof(device_binding_t));
    if (!obj) {
        return NULL;
    }
    obj->def = &OBJ_DEF;

    // TODO: object init

    return &obj->def;
}

void device_binding_object_release(const anjay_dm_object_def_t **def) {
    if (def) {
        device_binding_t *obj = get_obj(def);
        AVS_LIST_CLEAR(&obj->instances) {
            release_instance(obj->instances);
        }

        // TODO: object cleanup

        free(obj);
    }
}
